services:
  - type: web
    name: tourist-backend
    env: node
    rootDir: TouristBackend
    buildCommand: npm install
    startCommand: node server.js

  - type: web
    name: travel-frontend
    env: static
    rootDir: admin/panel
    buildCommand: npm install && npm run build
    staticPublishPath: dist